language: python

services:
  - docker

notifications:
  email: change

python:
    - "3.6"
install:
    - pip install flake8
    - pip install .
script:
  - flake8 --max-line-length=90 medium_speech
